#!/bin/bash

# invocation: add_candidates <input file> <dictionary> <number of candidates>
#
# reads lines formatted like 'Aasfresser<s n="n"/><s n="m"/>' from the input file
# and outputs the respective line followed by a line like
# '<e lm="Durchmesser">     <i>Durchmesser</i><par n="Abenteurer__n_m"/></e>'
# to standard output

oldIFS=$IFS
IFS=$'\n'
list=$(cat "$1")

truncate --size 0 bidix_only_with_candidates

for entry in $list; do
regex=$(echo -n "$entry" | sed -r 's/.*(....)<s n="n"\/><s n="([^"]*).*/<e lm="[^"]*\1">.*__n_\2"/')
echo "$entry"
grep -i -m "$3" "$regex" "$2"
done

IFS=$oldIFS
